### ISSUE TITLE
Incorrect working of datePatterns

### ISSUE THREAD

**Issue by aosipenko-sc** [OpusCapita/grailsflow-core-plugin#32]
Meta-Info | Value
-- | --
ExtProjectId | JCPROC-01
``` 
2019-08-07 14:08:06,791 [http-bio-14080-exec-10] ERROR (java.lang.Class) - Cannot convert 08-07-2019 to date.
java.text.ParseException: Unparseable date: "08-07-2019"
	at java.text.DateFormat.parse(DateFormat.java:366)
	at GrailsflowUtils.getParsedDate(GrailsflowUtils.groovy:48)
	at ProcessController.getStartOfParsedDate(ProcessController.groovy:889)
	at ProcessController.getSearchParameters(ProcessController.groovy:789)
	at ProcessController$_closure5.doCall(ProcessController.groovy:359)`
```
More details: [PROC-6996](https://support.jcatalog.com/browse/PROC-6996)

**Comment by ivouchak-sc** [comment]
Won't fix
Need to replace old static configuration beans from
```
<bean id="dateTimePatterns" class="java.util.HashMap">
    <constructor-arg value="#{formatPatterns.dateTimePatterns}"/>
  </bean>
```
to
```
<util:property-path id="dateTimePatterns" path="formatPatterns.dateTimePatterns"/>
```
Do it for rest format patterns configuration beans.

**Comment by ivouchak-sc** [comment]
The approach described above works only on GSP, but not in services, controllers and GSP.

**Comment by ivouchak-sc** [comment]
The following beans are not used anymore and should be removed:

- datePatterns
- dateTimePatterns
- numberPatterns
- decimalSeparators
Configuration for date patterns are moved into new bean **grailsflowFormatPatternsProvider**.
Custom date patterns could added in specific application by overriding this bean.

**Comment by ivouchak-sc** [comment]
The following beans are not used anymore and should be removed:

- datePatterns
- dateTimePatterns
- numberPatterns
- decimalSeparators

Configuration for date patterns are moved into `grailsflow.format`
